# Generated by Django 4.2.20 on 2025-05-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
