# Generated by Django 4.2.20 on 2025-05-22 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_REGISTERED', 'Người dùng mới đăng ký'), ('POST_CREATED', 'Bài viết mới được tạo'), ('POST_DELETED', 'Bài viết đã bị xóa'), ('USER_ROLE_CHANGED', 'Vai trò người dùng thay đổi'), ('EVENT_CREATED', 'Sự kiện mới được tạo'), ('REPORT_RESOLVED', 'Báo cáo đã được xử lý')], max_length=50, verbose_name='Loại hành động')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'ordering': ['-timestamp'],
            },
        ),
    ]
