# Generated by Django 4.2.20 on 2025-05-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_options_alter_comment_event_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_for_post_or_event_exclusive',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
    ]
