# Generated by Django 4.2.20 on 2025-05-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_original_event_creator_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='original_event_creator_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='shared_from_event',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_from',
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_event', to='core.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_sharing_this_event', to='core.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_from_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_sharing_this', to='core.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'Người dùng mới đăng ký'), ('POST_CREATED', 'Bài viết mới được tạo'), ('POST_DELETED', 'Bài viết đã bị xóa'), ('USER_ROLE_CHANGED', 'Vai trò người dùng thay đổi'), ('EVENT_CREATED', 'Sự kiện mới được tạo'), ('REPORT_RESOLVED', 'Báo cáo đã được xử lý'), ('EVENT_SHARED_AS_POST', 'Sự kiện được chia sẻ thành bài viết')], max_length=50, verbose_name='Loại hành động'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post__isnull', False), ('event__isnull', True)), models.Q(('post__isnull', True), ('event__isnull', False)), _connector='OR'), name='comment_for_post_or_event_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post__isnull', False), ('event__isnull', True)), models.Q(('post__isnull', True), ('event__isnull', False)), _connector='OR'), name='report_for_post_or_event_exclusive'),
        ),
    ]
