# Generated by Django 4.2.20 on 2025-05-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_options_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_for_post_or_event_exclusive',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='report_for_post_or_event_exclusive',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='event',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='original_event_creator_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='shared_from_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_events', to='core.event'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'Người dùng mới đăng ký'), ('POST_CREATED', 'Bài viết mới được tạo'), ('POST_DELETED', 'Bài viết đã bị xóa'), ('USER_ROLE_CHANGED', 'Vai trò người dùng thay đổi'), ('EVENT_CREATED', 'Sự kiện mới được tạo'), ('REPORT_RESOLVED', 'Báo cáo đã được xử lý')], max_length=50, verbose_name='Loại hành động'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
